# Generated by Django 3.0.4 on 2020-04-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitute',
            old_name='product',
            new_name='products',
        ),
    ]
