# Generated by Django 3.0.4 on 2020-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200406_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.TextField(null=True),
        ),
    ]
